---
enable_airgap: false

redpanda_admin_api_port: 9644
redpanda_kafka_port: 9092
redpanda_schema_registry_port: 8081
kafka_connect_port: 8083

http_port: 8080
https_port: 443

redpanda_group: redpanda
redpanda_user: redpanda

redpanda_base_url: "https://dl.redpanda.com"

redpanda_install_status: present # If redpanda_version is set to latest, changing redpanda_install_status to latest will effect an upgrade, otherwise the currently installed version will remain

redpanda_base_dir: /var/lib/redpanda
redpanda_data_directory: "{{ redpanda_base_dir }}/data"

redpanda_certs_dir: /etc/redpanda/certs
redpanda_csr_file: "{{ redpanda_certs_dir }}/node.csr"
redpanda_key_file: "{{ redpanda_certs_dir }}/node.key"
redpanda_cert_file: "{{ redpanda_certs_dir }}/node.crt"
redpanda_truststore_file: "{{ redpanda_certs_dir }}/truststore.pem"

# We default to use the same redpanda dirs, but in prod, a user can specify them directly
console_certs_dir: "{{ redpanda_certs_dir }}"
console_key_file: "{{ console_certs_dir }}/node.key"
console_cert_file: "{{ console_certs_dir }}/node.crt"

# the rpms
rp_key_rpm: "{{ redpanda_base_url }}/public/redpanda/gpg.988A7B0A4918BC85.key"
rp_standard_rpm: "{{ redpanda_base_url }}/public/redpanda/rpm/{{ rp_rpm_distro_map[ansible_distribution] | default('el') }}/{{ ansible_distribution_major_version }}/$basearch"
rp_noarch_rpm: "{{ redpanda_base_url }}/public/redpanda/rpm/{{ rp_rpm_distro_map[ansible_distribution] | default('el') }}/{{ ansible_distribution_major_version }}/noarch"
rp_source_rpm: "{{ redpanda_base_url }}/public/redpanda/rpm/{{ rp_rpm_distro_map[ansible_distribution] | default('el') }}/{{ ansible_distribution_major_version }}/SRPMS"
rp_rpm_distro_map:
  Fedora: fedora
  Amazon: amzn
  default: el


# the debs
rp_key_deb: "{{ redpanda_base_url }}/sMIXnoa7DK12JW4A/redpanda/gpg.988A7B0A4918BC85.key"
rp_key_deb_unstable: "{{ redpanda_base_url }}/E4xN1tVe3Xy60GTx/redpanda-unstable/gpg.39C20393EC2E8747.key"
rp_key_path_deb: "/usr/share/keyrings/redpanda-redpanda-archive-keyring.gpg"
rp_repo_signing_deb: "deb [signed-by=/usr/share/keyrings/redpanda-redpanda-archive-keyring.gpg] {{ redpanda_base_url }}/public/redpanda/deb/{{ansible_distribution | lower}} {{ ansible_distribution_release | lower }} main"
rp_repo_signing_src_deb: "deb-src [signed-by=/usr/share/keyrings/redpanda-redpanda-archive-keyring.gpg] {{ redpanda_base_url }}/public/redpanda/deb/{{ansible_distribution | lower}} {{ ansible_distribution_release | lower }} main"
