- name: Set data dir permissions
  ansible.builtin.file:
    dest: "{{ redpanda_base_dir }}"
    src: "{{ repdanda_mount_dir }}"
    state: link
    owner: redpanda
    group: redpanda
    mode: "0775"
  become: true
  tags:
    - data_dir_perms
